import {
  ArrowRight,
  ArrowUpRight,
  Menu,
  X,
  Code2,
  Globe,
  Smartphone,
  Bot,
  Cloud,
  Accessibility,
  TrendingUp,
  Users,
  CheckCircle2,
  Clock,
  BarChart3,
  Layers,
  Scaling,
  Headphones,
  ChevronDown,
  Search,
  FileText,
  Cpu,
  BookOpen,
  Newspaper,
  PlayCircle,
} from "lucide-react";
import type { LucideProps } from "lucide-react";

export const Icons: Record<string, React.FC<LucideProps>> = {
  ArrowRight,
  ArrowUpRight,
  Menu,
  X,
  Code2,
  Globe,
  Smartphone,
  Bot,
  Cloud,
  Accessibility,
  TrendingUp,
  Users,
  CheckCircle2,
  Clock,
  BarChart3,
  Layers,
  Scaling,
  Headphones,
  ChevronDown,
  Search,
  FileText,
  Cpu,
  BookOpen,
  Newspaper,
  PlayCircle,
};

export const iconSVG: Record<string, string> = {
  ArrowRight: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg>`,
  ArrowUpRight: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M7 17 17 7M7 7h10v10"/></svg>`,
  ChevronDown: `<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"/></svg>`,
};
